railswk2/DojoPizza/config/routes.rb
Rails.application.routes.draw do
  
  # get 'pizzas' => 'pizzas#index', as: 'pizzas'

  # get 'pizzas/new'

  # get 'pizzas/:id/edit' => 'pizzas#edit', as: 'editPizza'

  # get 'pizzas/:id' => 'pizzas#show', as: 'showPizza'

  # post 'pizzas' => 'pizzas#create'

  # post 'pizzas/:id' => 'pizzas#update'

  # delete 'pizzas/:id' => 'pizzas#destroy'
  
  # get 'pizzas/:pizza_id/customers/:id' => 'customers#show', as: 'pizza_customer' 

  resources :pizzas do
    resources :customers
  end

  root 'pizzas#index'
  get 'asdfasdf' => 'pizzas#asdfasdf'
end

railswk2/DojoPizza/app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :pizza
end

railswk2/DojoPizza/app/models/pizza.rb
class Pizza < ActiveRecord::Base
    validates :name, length: { minimum: 2 } , presence: true
    validates :address, length: { minimum: 2 } , presence: true

    has_many :customers
end

railswk2/DojoPizza/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def stu
    "HELLO FROM STU"
  end
  
  helper_method :stu
end

railswk2/DojoPizza/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    
    def show
        @pizza = Pizza.find(params[:pizza_id])
        @customer = Customer.find(params[:id])
    end

end

railswk2/DojoPizza/app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  layout 'pizzas_2Col', only: ['index']


  def asdfasdf
    @pizza = Pizza.new
    render 'update'
  end

  def index
    @color = "green"
    @pizzas = Pizza.all
    if flash[:errors]
      @errors = flash[:errors]
    end
  end

  def new
    if flash[:errors]
      @errors = flash[:errors]
    end
  end

  def edit
    @pizza = Pizza.find(params[:id])
  end

  def show
    @pizza = Pizza.find(params[:id])
    @customers = @pizza.customers
  end

  def create

    pizza = Pizza.create(pizzaParams)
    if pizza.errors.any? 
      flash[:errors] = pizza.errors.full_messages
      redirect_to new_pizza_url and return
    end

    redirect_to pizzas_url
  end

  def update
    pizza = Pizza.find(params[:id])
    pizza.name = pizzaParams[:name]
    pizza.address = pizzaParams[:address]
    pizza.city = pizzaParams[:city]
    pizza.state = pizzaParams[:state]
    pizza.save
    redirect_to pizza_url(id: params[:id])
  end

  def destroy
    pizza = Pizza.find(params[:id])
    pizza.destroy
    redirect_to pizzas_url
  end

  def pizzaParams
    params.require(:pizza).permit(:name,:address,:city,:state)
  end

  
end

railswk2/DojoPizza/app/helpers/customers_helper.rb
module CustomersHelper
end

railswk2/DojoPizza/app/helpers/pizzas_helper.rb
module PizzasHelper
end

railswk2/DojoPizza/app/views/pizzas/create.html.erb
<h1>Pizzas#create</h1>
<p>Find me in app/views/pizzas/create.html.erb</p>

railswk2/DojoPizza/app/views/pizzas/destroy.html.erb
<h1>Pizzas#destroy</h1>
<p>Find me in app/views/pizzas/destroy.html.erb</p>

railswk2/DojoPizza/app/views/pizzas/edit.html.erb
<%= render "customers/cus" %>
<%= stu %>

<form action="/pizzas/<%= @pizza.id%>" method='post'>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

    <input type="text" name="pizza[name]" value='<%= @pizza.name %>'>
    <input type="text" name="pizza[address]" value='<%= @pizza.address %>'>
    <input type="text" name="pizza[city]" value='<%= @pizza.city %>'>
    <input type="text" name="pizza[state]" value='<%= @pizza.state %>'>

    <input type="submit" value="Update">
    <a href='/pizzas/<%= @pizza.id %>'>Cancel</a >
</form>

railswk2/DojoPizza/app/views/pizzas/index.html.erb
<h1>Welcome to Dojo Pizzas</h1>
<img src="<%= asset_path 'kitty.jpg' %>" alt="an awesome kitty">

<% if @errors %>
    <% @errors.each do |error| %>
        <h3 class = 'danger'><%= error %></h3>
    <% end %>
<% end %>
<a href='/pizzas/new'>Add a Parlor</a>



<% content_for :right do %>
<table>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Actions</th>
    <% @pizzas.each do |pizza|  %>
    <tr>
        <td><%= pizza.name %></td>
        <td><%= pizza.address %></td>
        <td><%= pizza.city %></td>
        <td><%= pizza.state %></td>
        <td>
        
        <a href="/pizzas/<%= pizza.id %>">Show</a>
        |
        <a href="/pizzas/<%= pizza.id %>/edit">Edit</a>
        <form action='/pizzas/<%= pizza.id%>' method='post'>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <input type="hidden" name="_method" value="delete">
            <input class='danger' type="submit" value="DESTROY">
        </form>
        
        </td>
    </tr>
    <% end %>
</table>
<% end %>



<% content_for :left, "THIS IS ON THE LEFT" %>

railswk2/DojoPizza/app/views/pizzas/new.html.erb
<h1>Please Create A New Franchise</h1>
<% if @errors %>
    <% @errors.each do |error| %>
        <h3 class = 'danger'><%= error %></h3>
    <% end %>
<% end %>
<form action="/pizzas" method='post'>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

    <input type="text" name="pizza[name]" placeholder='Name'>
    <input type="text" name="pizza[address]" placeholder='Address'>
    <input type="text" name="pizza[city]" placeholder='City'>
    <input type="text" name="pizza[state]" placeholder='State'>

    <input type="submit" value="Create">

</form>

railswk2/DojoPizza/app/views/pizzas/show.html.erb
<h1><%= @pizza.name %></h1>
<h3><%= @pizza.address%></h3>
<h3><%= @pizza.city%>, <%= @pizza.state%></h3>

<ul>
    <% @customers.each do |cus| %>
        <li><%= cus.name %> : <%= cus.purchases %> | <%= link_to 'Show', pizza_customer_path(pizza_id: @pizza.id, id: cus.id) %></li>
        
    <% end %>
</ul>

<a href="/pizzas/<%= @pizza.id %>/edit">Edit</a>

railswk2/DojoPizza/app/views/pizzas/update.html.erb
<%= form_for(@pizza) do |f| %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_area :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_area :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railswk2/DojoPizza/app/views/shared/_header.html.erb
<h1>This is my Header version 2</h1>